In [21]:
import matplotlib.pyplot as plt
import numpy

In [ ]:
#1
names = ['group_a', 'group_b', 'group_c']
values = [1, 100, 10]

plt.bar(names, values)
plt.suptitle('Categorical Plotting')
plt.show()

In [2]:
#3
print(type(1 + 5. ** 4* 2 + 3))

<class 'float'>


In [3]:
#4
print(bin(10))

0b1010


In [ ]:
#5
names = ['group_a', 'group_b', 'group_c']
values = [1, 10, 100]

plt.bar(names, values)
plt.suptitle('Categorical Plotting')
plt.show()

In [5]:
#10
print(hex(15))

0xf


In [6]:
#11
x =  ["a","e","i","o","u"]
for y in x:
  print(y, end = " ")

a e i o u 

In [7]:
#12
L = (1,3,1,4,5)
T = (1,2,3)
print(T*2 + L)

(1, 2, 3, 1, 2, 3, 1, 3, 1, 4, 5)


In [8]:
#13
x = " 5, 4, 3, 2, 1]"
y = "[1, 2, 3, 4,"
print(y + x)

[1, 2, 3, 4, 5, 4, 3, 2, 1]


In [9]:
#14
x = {'a':1, 'e':2, 'i':3, 'o':4, 'u':5}
for y in x:
  print(y, end = " ")

a e i o u 

In [10]:
#16
x = 0o3745
print(x)

2021


In [11]:
#17
b = numpy.linspace(-360,0,5)
print(b/90)

[-4. -3. -2. -1.  0.]


In [12]:
#19
print(type(20))

<class 'int'>


In [ ]:
#20
names = ['group_a', 'group_b', 'group_c']
values = [1, 100, 10]

plt.plot(names, values)
plt.suptitle('Categorical Plotting')
plt.show()

In [14]:
#22
x = [1, 2, 3, 4, 5]
for y in range(4,-1,-1):
  print(x[y], end = " ")

5 4 3 2 1 

In [15]:
#24
a = numpy.arange(12)*2
i = numpy.array([1, 1, 3, 8, 5])
print(a[i])

[ 2  2  6 16 10]


In [16]:
#25
x = {'a':1, 'e':2, 'i':3, 'o':4, 'u':5}
for y in x:
   print(x[y], end = " ")

1 2 3 4 5 

In [17]:
#26
int('1011',2)

11

In [18]:
#31
x = 0b1101
y = 7
z = x+y
print(z)

20


In [19]:
#35
Dict = {'3':3,'grade':3.2,'height':1.78,3:['3'],4:4}
Dict['3'] = Dict[4]
print(Dict.get(3))

['3']


In [20]:
#37
print(bin(10))

0b1010


In [22]:
#38
b = numpy.linspace(0,360,5)
print(b/90)

[0. 1. 2. 3. 4.]


In [26]:
#40
import pandas as pd
values_list = [[20, 3, 45, 23],
               [33, 6, 10, 8],
               [45, 26, 21, 34],
               [18, 44, 32, 1]]

# creating a pandas dataframe
data = pd.DataFrame(values_list, columns=['A', 'B', 'C', 'D'])
data.apply(lambda x: x.count() - x.max())

A   -41
B   -40
C   -41
D   -30
dtype: int64